- type: custom-api
  define: &home-assistant-entity
    cache: 1s
    headers:
      Accept: application/json
      Authorization: Bearer ${HOMEASSISTANT_KEY}
  title: Weather
  title-url: ${HOMEASSISTANT_URL}/dashboard-main/weather
  url: https://${HOMEASSISTANT_ENTITY_ENDPOINT}/weather.weather_home
  <<: *home-assistant-entity
  subrequests:
    bedroom:
      url: https://${HOMEASSISTANT_ENTITY_ENDPOINT}/sensor.bedroom_temperature_temperature
      <<: *home-assistant-entity
    living-room:
      url: https://${HOMEASSISTANT_ENTITY_ENDPOINT}/sensor.living_room_temperature_temperature
      <<: *home-assistant-entity
  template: | #html
    {{ $hour := now.Hour }}
    {{ $isDay := and (ge $hour 6) (lt $hour 18) }}
    {{ $phase := "day" }}
    {{ if not $isDay }}
      {{ $phase := "night" }}
    {{ end }}

    {{ $weatherState := .JSON.String "state" }}
    {{ $weatherIcon := $weatherState }}
    {{ if ne ($weatherState | findMatch "clear") "" }}
      {{ $weatherIcon = concat "clear-" $phase }}
    {{ else if ne ($weatherState | findMatch "cloudy") "" }}
      {{ $weatherIcon = concat "cloudy-3-" $phase }}
    {{ else if ne ($weatherState | findMatch "rainy") "" }}
      {{ $weatherIcon = concat "rainy-3-" $phase }}
    {{ else if ne ($weatherState | findMatch "fog") "" }}
      {{ $weatherIcon = concat "fog-" $phase }}
    {{ else if ne ($weatherState | findMatch "isolated-thunderstorms") "" }}
      {{ $weatherIcon = concat "isolated-thunderstorms-" $phase }}
    {{ else if ne ($weatherState | findMatch "scattered-thunderstorms") "" }}
      {{ $weatherIcon = concat "scattered-thunderstorms-" $phase }}
    {{ else if ne ($weatherState | findMatch "lightning") "" }}
      {{ $weatherIcon = "thunderstorms" }}
    {{ else if ne ($weatherState | findMatch "sunny") "" }}
      {{ $weatherIcon = "clear-day" }}
    {{ end }}

    {{ $weatherStateString := $weatherState }}
    {{ if eq $weatherState "partlycloudy" }}
      {{ $weatherStateString := "Partly Cloudy" }}
    {{ end }}

    <div class="flex flex-column gap-5">
      <div class="flex gap-20 items-center weather-img-container">
        <img src="${WEATHER_ICONS}/{{ $weatherIcon }}.svg" loading="lazy" alt="">
        <strong class="size-h4 block capitalize weather-state">{{ $weatherStateString }}</strong>
      </div>
      <div class="flex justify-between text-center">
        <div class="shrink min-width-0">
            <div class="color-highlight size-h4 weather-temperature">{{ .JSON.Float "attributes.temperature" | formatNumber }}{{ .JSON.String "attributes.temperature_unit" }}</div>
            <div class="text-very-compact uppercase">Weather</div>
        </div>
        {{ $bedroomEntity := .Subrequest "bedroom" }}
        <div class="shrink min-width-0 target-gone">
            <div class="color-highlight size-h4 bedroom-temperature">{{ $bedroomEntity.JSON.Float "state" | formatNumber }}{{ $bedroomEntity.JSON.String "unit_of_measurement" }}</div>
            <div class="text-very-compact uppercase">Bedroom</div>
        </div>
        {{ $livingRoomEntity := .Subrequest "living-room" }}
        <div class="shrink min-width-0">
            <div class="color-highlight size-h4 living-room-temperature">{{ $livingRoomEntity.JSON.Float "state" | formatNumber }}{{ $livingRoomEntity.JSON.String "unit_of_measurement" }}</div>
            <div class="text-very-compact uppercase">Living Room</div>
        </div>
      </div>
    </div>